[tool.coverage.run]
branch = true
parallel = true
source_pkgs = ["deadline"]
include = ["*/deadline/client/ui/*"]
plugins = ["coverage_conditional_plugin"]

[tool.coverage.paths]
source = ["src/"]

[tool.coverage.report]
show_missing = true
fail_under = 50

[tool.coverage.coverage_conditional_plugin.rules]
# This cannot be empty otherwise coverage-conditional-plugin crashes with:
# AttributeError: 'NoneType' object has no attribute 'items'
#
# =========== WARNING TO REVIEWERS ============
#
# Any rules added here are ran through Python's
# eval() function so watch for code injection
# attacks.
#
# =========== WARNING TO REVIEWERS ============
