name: "\U0001F41B Bug Report"
description: Report a bug
title: "Bug: TITLE"
labels: ["bug"]
body:
  - type: textarea
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
    validations:
      required: true

  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps
    validations:
      required: true

  - type: textarea
    id: code_snippet
    attributes:
      label: Code Snippet
    validations:
      required: true

