
name: "📕 Documentation Issue"
description: Issue in the documentation
title: "Docs: (short description of the issue)"
labels: ["documenation", "needs triage"]
body:
  - type: textarea
    id: documentation_issue
    attributes:
      label: Documentation Issue
      description: Describe the issue
    validations:
      required: true