[package]
name = "deadline-cli"
description = "AWS Deadline Cloud CLI"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "deadline"
path = "src/main.rs"

[dependencies]
deadline-models = { workspace = true }
deadline-common = { workspace = true }
deadline-config = { workspace = true }
deadline-client = { workspace = true }
deadline-job-attachments = { workspace = true }
deadline-job-bundle = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
textwrap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
libc = { workspace = true }
thiserror = { workspace = true }
indicatif = { workspace = true }

[dev-dependencies]
deadline-test-server = { workspace = true }
assert_cmd = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
