[package]
name = "deadline-job-bundle"
description = "Job bundle loading and parameter handling for AWS Deadline Cloud"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deadline-models = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-case = { workspace = true }
