[package]
name = "deadline-job-bundle"
description = "Job bundle loading and parameter handling for AWS Deadline Cloud"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deadline-api = { workspace = true }
deadline-job-attachments = { workspace = true }
deadline-config = { workspace = true }
aws-sdk-deadline = { workspace = true }
libc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
test-case = { workspace = true }

[lints]
workspace = true
