[package]
name = "deadline-common"
description = "Common utilities for AWS Deadline Cloud"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deadline-models = { workspace = true }
deadline-config = { workspace = true }
serde_json = { workspace = true }
uuid = { version = "1", features = ["v4"] }
ureq = "3"
log = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
wiremock = { workspace = true }
tokio = { workspace = true }
