[package]
name = "deadline-models"
description = "Shared types and error definitions for AWS Deadline Cloud"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
