[package]
name = "deadline-python-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "_native"
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "0.24", features = ["abi3-py39"] }
pythonize = "0.24"
deadline-config = { workspace = true }
deadline-api = { workspace = true }
deadline-job-bundle = { workspace = true }
deadline-job-attachments = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
