name: "Build Installers"

on:
  workflow_dispatch:
    inputs:
      os:
        required: true
        default: "linux"
        type: choice
        options:
        - Linux
        - Windows
        - MacOS
      ref_type:
        required: true
        type: choice
        options:
        - heads
        - tags
      ref:
        required: true
        type: string
        default: "mainline"
      environment:
        required: true
        type: choice
        options:
        - mainline
        - release

jobs:
  BuildInstaller:
    if: (github.repository == 'aws-deadline/deadline-cloud')
    name: Build Installer
    uses: aws-deadline/.github/.github/workflows/reusable_build_installers.yml@mainline
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: ${{inputs.environment}}
      ref_type: ${{inputs.ref_type}}
      ref: ${{inputs.ref}}
      oses: "['${{inputs.os}}']"
      project_name: "deadline-cloud"
