name: Code Quality

on:
  pull_request:
    branches: [ mainline, release, feature_assets_cli ]
  workflow_call:
    inputs:
      branch:
        required: false
        type: string

jobs:
  Test:
    name: Python
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    uses: aws-deadline/.github/.github/workflows/reusable_python_build.yml@mainline
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}