name: Import Dependency Check

on:
  pull_request:
    branches: [ mainline, release, feature_*, 'patch_*' ]

jobs:
  check-import-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install hatch
        run: pip install hatch

      - name: Check import dependencies
        run: hatch run check-imports
