name: Integ Tests

on:
  workflow_dispatch:

jobs:
  Integ:
    runs-on: ubuntu-latest
    environment: mainline
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_CODEBUILD_MAINLINE_INTEG_ROLE }}
          aws-region: us-west-2
      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: deadline-cloud-dev-IntegTest
          hide-cloudwatch-logs: true