name: Mainline Integration Test

on:
  workflow_dispatch:

jobs:  
  MainlineLinuxIntegrationTest:
    name: Linux Integration Test
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_integration_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      branch: mainline
      environment: mainline
      os: linux