name: MkDocs Quality Check

on:
  pull_request:
    branches: [ mainline, release, feature_assets_cli, 'patch_*' ]
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
      tag:
        required: false
        type: string
permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Hatch
        run: |
          pip install --upgrade hatch

      - name: Build documentation
        run: hatch run docs:build
