name: Build and Deploy MkDocs

on:
  push:
    branches:
      - mainline
    paths:
      - 'docs/**'
      - 'src/**'
      - 'mkdocs.yml'
      - '.github/workflows/mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Hatch
        run: |
          pip install --upgrade hatch

      - name: Build and deploy documentation
        run: hatch run docs:deploy --force
