name: "Release: Publish"
run-name: "Release: ${{ github.event.head_commit.message || inputs.tag }}"

on:
  push:
    branches:
      - mainline
    paths:
      - CHANGELOG.md
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string
        description: Specify a tag to re-run a release.

concurrency:
  group: release

permissions:
  contents: read

jobs:
  TagRelease:
    uses: aws-deadline/.github/.github/workflows/reusable_tag_release.yml@mainline
    secrets: inherit
    with:
      tag: ${{ github.event_name == 'workflow_dispatch' && inputs.tag || '' }}

  UnitTests:
    name: Unit Tests
    needs: TagRelease
    uses: ./.github/workflows/code_quality.yml
    with:
      tag: ${{ needs.TagRelease.outputs.tag }}

  LinuxIntegrationTests:
    name: Linux Integration Tests
    needs: [TagRelease, UnitTests]
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_integration_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      environment: release
      os: linux
      tag: ${{ needs.TagRelease.outputs.tag }}

  WindowsIntegrationTests:
    name: Windows Integration Tests
    needs: [TagRelease, UnitTests]
    permissions:
      id-token: write
      contents: read
    uses: aws-deadline/.github/.github/workflows/reusable_integration_test.yml@mainline
    secrets: inherit
    with:
      repository: ${{ github.event.repository.name }}
      environment: release
      os: windows
      tag: ${{ needs.TagRelease.outputs.tag }}

  PreRelease:
    needs: [TagRelease, LinuxIntegrationTests, WindowsIntegrationTests]
    uses: aws-deadline/.github/.github/workflows/reusable_prerelease.yml@mainline
    permissions:
      id-token: write
      contents: write
    secrets: inherit
    with:
        tag: ${{ needs.TagRelease.outputs.tag }}

  BuildAndStageInstallers:
    needs: [TagRelease, PreRelease]
    uses: aws-deadline/.github/.github/workflows/reusable_build_and_stage_installers.yml@mainline
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      project_name: ${{ github.event.repository.name }}
      tag: ${{ needs.TagRelease.outputs.tag }}
      oses: "['Linux', 'Windows', 'MacOS']"

  Release:
    needs: [TagRelease, BuildAndStageInstallers]
    uses: aws-deadline/.github/.github/workflows/reusable_release.yml@mainline
    secrets: inherit
    permissions:
      id-token: write
      contents: write
    with:
        tag: ${{ needs.TagRelease.outputs.tag }}
  
  Publish:
    needs: [TagRelease, Release]
    uses: aws-deadline/.github/.github/workflows/reusable_publish_python.yml@mainline
    permissions:
      id-token: write
    secrets: inherit
    with:
        tag: ${{ needs.TagRelease.outputs.tag }}
  

  # PyPI does not support reusable workflows yet
  # # See https://github.com/pypi/warehouse/issues/11096
  PublishToPyPI:
    needs: [TagRelease, Publish]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ needs.TagRelease.outputs.tag }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install --upgrade hatch
      - name: Build
        run: hatch -v build
      # # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
