name: "Release: Bump"

on:
  schedule:
    # Every Monday at 14:00 UTC (~6/7am Pacific, ~9/10am Eastern).
    - cron: "0 14 * * 1"
  workflow_dispatch:
    inputs:
      force_version_bump:
        required: false
        default: ""
        type: choice
        options:
        - ""
        - patch
        - minor
        - major

concurrency:
  group: release

jobs:
  Bump:
    name: Version Bump
    uses: aws-deadline/.github/.github/workflows/reusable_bump.yml@mainline
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    secrets: inherit
    with:
      force_version_bump: ${{ inputs.force_version_bump }}