name: "Release: Bump"

on:
  workflow_dispatch:
    inputs:
      force_version_bump:
        required: false
        default: ""
        type: choice
        options:
        - ""
        - patch
        - minor
        - major

concurrency:
  group: release

jobs:
  UnitTests:
    name: Unit Tests
    uses: ./.github/workflows/code_quality.yml
    with:
      branch: mainline

  Bump:
    name: Version Bump
    needs: UnitTests
    uses: aws-deadline/.github/.github/workflows/reusable_bump.yml@mainline
    secrets: inherit
    with:
      force_version_bump: ${{ inputs.force_version_bump }}